def psoSCrBjPNenAouVvezomNfQcKVqZPhWESJQHz(jbFPBHGQurayfOSFeNCGjGeiVdWGsipXEiTdHJpzzbFPBHGQurayfOSFeNCGjGeiVdWGsipXEiTCoDsrbFPBHGQurayfOSFeNCGjGeiVdWGsipXEiTointTVteaEcvedcpsDFOUIbjUjXSFDaKQOPwhNqcgRxTvZxHHQcnRBEJAMTpcQgQwTlfAupsDFOUIbjUjXSFDaKQOPwhNqcgRxTvZxHHQcnRBEJAMTpcQgJAOWfAdM):
	print(jbFPBHGQurayfOSFeNCGjGeiVdWGsipXEiTdHJpzzbFPBHGQurayfOSFeNCGjGeiVdWGsipXEiTCoDsrbFPBHGQurayfOSFeNCGjGeiVdWGsipXEiTointTVteaEcvedcpsDFOUIbjUjXSFDaKQOPwhNqcgRxTvZxHHQcnRBEJAMTpcQgQwTlfAupsDFOUIbjUjXSFDaKQOPwhNqcgRxTvZxHHQcnRBEJAMTpcQgJAOWfAdM)
def zuukoQTqYelrcwtyPExFtSKMfkhRSlWeoEMCeoQymSqc(psDFOUIbjUjXSFDaKQOPwhNqcgRxTvZxHHQcnRBEJAMTpcQg, bFPBHGQurayfOSFeNCGjGeiVdWGsipXEiT, uAFuiFpsDFOUIbjUjXSFDaKQOPwhNqcgRxTvZxHHQcnRBEJAMTpcQgWEEbBedhzsuaCwEOgDdniHTKjibdNcjLwgKaBijLVdw):
	print("This is definitelbFPBHGQurayfOSFeNCGjGeiVdWGsipXEiT not a function.") 
WXdKOqSOfHOKpZUTbDmVISJWJTnsINvcesnkoqomGzlUw, NbklVFBTiVLbFPBHGQurayfOSFeNCGjGeiVdWGsipXEiTGpiqAdYaHYpYbZEDwviaheGITBfBmJGYzONN = 1
lEcMvOgBqriQBSIDpeOMIDfMVnCtpDWQynPQzNKHJClMwm=2
