import codecs
import cmath
JoSLohHsipHVoTyiYfFkMyuxpfthRAOtfwStPXSLGBF = 1
dCCZqUSLPbZOqFUIjZvXgwNwiuuBEw = 5
xXBYygjcDKTQVDqQlHlEBARwTnCszpnWGkjMpdWLZfLVYEc = 6
pyFMiTUpqCrqzZNGHWnvFgaMoWkFwVg = (dCCZqUSLPbZOqFUIjZvXgwNwiuuBEw**2) - (4*JoSLohHsipHVoTyiYfFkMyuxpfthRAOtfwStPXSLGBF*xXBYygjcDKTQVDqQlHlEBARwTnCszpnWGkjMpdWLZfLVYEc)
oiXlIYCxfdJqHdfohChOzmufAQIukPHkVKPrVVEeMn = (-dCCZqUSLPbZOqFUIjZvXgwNwiuuBEw-cmath.sqrt(pyFMiTUpqCrqzZNGHWnvFgaMoWkFwVg))/(2*JoSLohHsipHVoTyiYfFkMyuxpfthRAOtfwStPXSLGBF)
OQIZeTDpdVnpahgyeEUmACQYctwospDXjghFjsWSEPvtbudFEH = (-dCCZqUSLPbZOqFUIjZvXgwNwiuuBEw+cmath.sqrt(pyFMiTUpqCrqzZNGHWnvFgaMoWkFwVg))/(2*JoSLohHsipHVoTyiYfFkMyuxpfthRAOtfwStPXSLGBF)
print('The solution are {0} and {1}'.format(oiXlIYCxfdJqHdfohChOzmufAQIukPHkVKPrVVEeMn,OQIZeTDpdVnpahgyeEUmACQYctwospDXjghFjsWSEPvtbudFEH))
